# Generated by Django 4.0 on 2023-06-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='dsaf', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
